import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowUp,Check,ChevronRight,Play,Pause,Maximize2,Minimize2,Eye,EyeOff,LayoutGrid,ListTodo,GitBranch,FileText,ShieldCheck,X,MessageSquare,Clock,CornerDownRight} from 'lucide-react';
import OfficeScene,{Avatar} from '../components/OfficeScene';
import {TEAM,INITIAL_ACTIVITY} from '../data/team';

export default function SecurityOffice({onNavigate,onOpenFinding,onEscalate,escalated,findings}){
 const [selected,setSelected]=useState(null),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1),[labels,setLabels]=useState(true),[tab,setTab]=useState('office'),[expanded,setExpanded]=useState(false);
 const [input,setInput]=useState(''),[typing,setTyping]=useState(false),[mission,setMission]=useState('idle'),[stage,setStage]=useState(0),[activity,setActivity]=useState(INITIAL_ACTIVITY);
 const [messages,setMessages]=useState([{who:'atlas',text:"Morning, Chiranthan. Your team is reviewing Juice Shop. There are 3 critical issues that need attention. I’m coordinating the review."},{who:'atlas',text:'Start with the product-search issue. Nova found related activity in the honeypot, so we’ve moved it to the top of the queue.',action:'finding'}]);
 const timers=useRef([]),end=useRef(null),chatInput=useRef(null);
 const later=(fn,ms)=>{timers.current.push(setTimeout(fn,ms))};
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[messages,typing]);
 const worker=TEAM.find(p=>p.id===selected),openCount=findings.filter(f=>f.status!=='Resolved').length;
 function addActivity(name,text,tone='normal'){setActivity(a=>[{name,text,time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),tone},...a].slice(0,8))}
 function startReview(){
 if(mission==='running')return;
 setMission('running');setStage(0);addActivity('ATLAS','Started a new demonstration review.');
 setMessages(m=>[...m,{who:'atlas',text:'Review assigned. Sage is checking code, Bolt is inspecting packages, Cipher is checking for secrets and Echo is testing staging. Nova will review their evidence.'}]);
 const steps=[['SAGE','Code checks complete. Evidence handed to Nova.'],['BOLT','Dependency checks complete. Package findings handed to Nova.'],['CIPHER','Secrets review complete. One potential key needs a human check.'],['ECHO','Staging checks complete. Nova is assessing the combined evidence.'],['NOVA','Risk review complete. Product-search issue remains the first priority.'],['ATLAS','Security brief prepared. Escalation is waiting for your approval.']];
 steps.forEach(([name,text],i)=>later(()=>{setStage(i+1);addActivity(name,text);if(i===5){setMission('done');setMessages(m=>[...m,{who:'atlas',text:'The demonstration review is complete. Your security brief is ready. The product-search issue needs a developer review; nothing has been sent externally.',action:'report'}]);}},(i+1)*2000));
 }
 function send(text=input){
 const value=text.trim();if(!value||typing)return;setInput('');setMessages(m=>[...m,{who:'you',text:value}]);setTyping(true);
 later(()=>{
 setTyping(false);const q=value.toLowerCase();let answer,action;const namedWorker=TEAM.find(p=>q.includes(p.name.toLowerCase()));
 if(/scan|start.*review|assign|check.*code|start/.test(q)){startReview();return;}
 if(namedWorker){answer=`${namedWorker.name} is your ${namedWorker.role.toLowerCase()}. ${mission==='done'?'The review is complete.':namedWorker.task+'.'} ${namedWorker.description}`;}
 else if(/report|summary|brief/.test(q)){answer=`The sample workspace has ${openCount} unresolved findings. Product-search injection and a possible exposed credential need attention first. Here is the security brief with the evidence and next steps.`;action='report';}
 else if(/escalat|notify|send/.test(q)){answer=escalated?'The escalation has been recorded in this demo. No email or external message was sent.':'I’ve prepared an escalation for the product-search issue. You can review the owner, evidence and suggested action before approving it.';action='escalation';}
 else if(/critical|risk|priorit|safe|urgent|first|attention/.test(q)){answer='The product-search endpoint may let someone change a database query. Related honeypot activity increases its priority; it does not prove your application was compromised. A developer should review the query and use parameterized inputs.';action='finding';}
 else if(/team|who|worker|agent|doing/.test(q)){answer='I coordinate assignments and reports. Nova reviews risk. Sage, Bolt, Cipher and Echo run fixed checks using Semgrep, Trivy, Gitleaks and ZAP. Only Nova and I are AI roles in the planned product.';}
 else {answer='This prototype supports a few sample conversations. Try “What needs attention?”, “Start a security review”, “Prepare a report” or “Escalate the critical issue”. A real manager agent can be connected later.';}
 setMessages(m=>[...m,{who:'atlas',text:answer,action}]);
 },650);
 }
 function actionButton(action){if(action==='finding')return <button className="message-action" onClick={()=>onOpenFinding('AEG-1042')}>Review priority issue <ArrowUpRight size={14}/></button>;
 if(action==='report')return <button className="message-action" onClick={()=>onNavigate('reports')}>Open security brief <ArrowUpRight size={14}/></button>;
 if(action==='escalation')return <button className="message-action" onClick={()=>onNavigate('reports')}>Review escalation <ArrowUpRight size={14}/></button>;return null;}
 const stageText=['Assigning specialists','Inspecting source code','Auditing dependencies','Checking secrets','Reviewing web evidence','Preparing security brief','Review complete'][stage];
 return <div className={`office-page ${expanded?'office-expanded':''}`}>
 <div className="page-heading"><div><div className="eyebrow">YOUR SECURITY OPERATIONS, IN ONE PLACE</div><h1>The security office<span className="heading-dot">.</span></h1><p>A small team. A clear view of what matters.</p></div><button className="accent-button" onClick={startReview} disabled={mission==='running'}><Play size={15}/>{mission==='running'?'Review in progress':'Start team review'}</button></div>
 <div className="office-layout">
 <div className="office-left">
 <section className="office-shell">
 <div className="office-toolbar"><div className="view-tabs"><button className={tab==='office'?'active':''} onClick={()=>setTab('office')}><LayoutGrid size={15}/>Office</button><button className={tab==='tasks'?'active':''} onClick={()=>setTab('tasks')}><ListTodo size={15}/>Task board</button></div><div className="office-meta"><span className="demo-live-dot"/>6 team members<span className="tiny-divider"/><span>2 AI · 4 workers</span></div></div>
 <div className="mission-hud"><span className="pixel-name">MISSION 01</span><span>{mission==='running'?stageText:mission==='done'?'Security review complete':'Review the staging workspace'}</span><div aria-label={`${stage} of 6 review steps complete`}>{TEAM.map((p,i)=><i key={p.id} className={stage>i?'filled':''}/>)}</div><b>{stage}/6</b></div><div className="floor-topline"><span><GitBranch size={13}/> juice-shop <i>/</i> staging</span><span className="floor-label">FLOOR 01 <span>—</span> AEGIS HQ</span></div>
 {tab==='office'?<div className="scene-wrap"><OfficeScene selected={selected} onSelect={setSelected} paused={paused} speed={speed} labels={labels} mission={mission}/><div className="scene-caption"><span className="keycap">↖</span> Select a teammate to see their work</div><div className="scene-controls"><button onClick={()=>setPaused(!paused)} aria-label={paused?'Resume movement':'Pause movement'} title={paused?'Resume movement':'Pause movement'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button onClick={()=>setSpeed(speed===1?2:1)} aria-label="Change movement speed">{speed}×</button><button onClick={()=>setLabels(!labels)} aria-label={labels?'Hide names':'Show names'} title="Toggle names">{labels?<Eye size={15}/>:<EyeOff size={15}/>}</button><button onClick={()=>setExpanded(!expanded)} aria-label={expanded?'Exit expanded office':'Expand office'}>{expanded?<Minimize2 size={15}/>:<Maximize2 size={15}/>}</button></div></div>:<div className="task-board">{(mission==='done'?['Completed checks','Reviewed','Ready for approval']:['In progress','Under review','Ready for approval']).map((name,i)=><div className="task-column" key={name}><h3><span className={`task-status s${i}`}/>{name}<b>{i===0?4:1}</b></h3>{(i===0?TEAM.slice(2):[TEAM[i===1?1:0]]).map(p=><button className="task-card" key={p.id} onClick={()=>setSelected(p.id)}><span className="task-tool">{p.tool}</span><h4>{i===2?'Prepare the critical-issue escalation':p.task}</h4><div><Avatar person={p} size={28}/><span className="pixel-name" style={{color:p.color}}>{p.name}</span><ChevronRight size={14}/></div></button>)}</div>)}</div>}
 <div className="office-status"><span><span className="demo-live-dot"/>{mission==='running'?stageText:mission==='done'?'Review complete · brief ready':'Team on duty'}</span><span><ShieldCheck size={13}/> Human approval before escalation</span></div>
 </section>
 <div className="roster-heading"><h2>Meet your team <span>06</span></h2><span>Brains + reliable tools</span></div>
 <div className="team-roster">{TEAM.map(p=><button key={p.id} className={`team-card ${selected===p.id?'selected':''}`} style={{'--person':p.color}} onClick={()=>setSelected(selected===p.id?null:p.id)}><div className="team-card-top"><div className="avatar-tile"><Avatar person={p}/></div><span className={p.type==='AI agent'?'agent-badge':'worker-badge'}>{p.type==='AI agent'?'AI':'RULES'}</span></div><div className="pixel-name">{p.name}</div><div className="team-role">{p.role}</div><div className="team-task"><span/>{mission==='done'?'Review complete':p.tool}</div></button>)}</div>
 {worker&&<section className="worker-inspector" style={{'--person':worker.color}}><div className="inspector-identity"><Avatar person={worker} size={64}/><div><span className="pixel-name">{worker.name}</span><h3>{worker.role}</h3><span className="muted">{worker.type} · {worker.tool}</span></div><button className="icon-button inspector-close" aria-label="Close team member details" onClick={()=>setSelected(null)}><X size={16}/></button></div><p>{worker.description}</p><div className="worker-assignment"><span>CURRENT ASSIGNMENT</span><strong>{mission==='done'?'Review complete — awaiting next assignment':worker.task}</strong><div className="worker-progress"><i style={{width:`${mission==='done'?100:worker.progress}%`}}/></div></div><button className="text-button" onClick={()=>{setInput(`What is ${worker.name} working on?`);chatInput.current?.focus()}}>Ask Atlas about this teammate <ArrowUpRight size={14}/></button></section>}
 <section className="office-bottom"><div className="activity-section"><div className="section-heading"><h2>From the office floor</h2><span>Activity log</span></div>{activity.slice(0,3).map((a,i)=><div className="activity-item" key={a.time+a.text}><span className={`activity-line-dot ${a.tone}`}/><div><span className="pixel-small">{a.name}</span><p>{a.text}</p></div><time>{a.time}</time></div>)}</div><div className="attention-card"><span className="attention-kicker"><span/>WAITING FOR YOU</span><h3>{escalated?'Escalation recorded':'One decision, real impact.'}</h3><p>{escalated?'Your approval is saved for this session. No external message was sent.':'Atlas has prepared an escalation for the product-search issue.'}</p><button onClick={()=>onNavigate('reports')}>{escalated?'View approval record':'Review escalation'}<ArrowUpRight size={16}/></button></div></section>
 </div>
 <aside className="manager-panel"><div className="manager-header"><div className="manager-portrait"><Avatar person={TEAM[0]} size={52}/></div><div><div className="manager-name">Atlas <span>MANAGER</span></div><span className="manager-available"><span/>At your desk</span></div><MessageSquare size={18} className="muted"/></div><div className="conversation-label"><span>DIRECT CONVERSATION</span><span>Today</span></div><div className="chat-messages" role="log" aria-label="Conversation with Atlas" aria-live="polite">{messages.map((m,i)=><div className={`chat-message ${m.who}`} key={i}><div className="message-name">{m.who==='you'?'YOU':'ATLAS'}<span>{m.who==='atlas'?'Security manager':''}</span></div><p>{m.text}</p>{actionButton(m.action)}</div>)}{typing&&<div className="typing">Atlas is preparing a response<span>•••</span></div>}<div ref={end}/></div><div className="chat-bottom"><div className="chat-prompts">{['What needs attention?','Prepare a report'].map(q=><button key={q} onClick={()=>send(q)} disabled={typing}>{q}<ArrowUpRight size={12}/></button>)}</div><form className="chat-composer" onSubmit={e=>{e.preventDefault();send()}}><label className="sr-only" htmlFor="manager-message">Message Atlas</label><textarea id="manager-message" ref={chatInput} rows={2} placeholder="Ask Atlas, in your own words…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div><span>No security jargon needed</span><button type="submit" aria-label="Send message" disabled={!input.trim()||typing}><ArrowUp size={17}/></button></div></form><div className="chat-disclaimer">Interactive demo · scripted replies</div></div></aside>
 </div>
 </div>;
}
